name: Build jar with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # or adopt, zulu, etc.
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        

      - name: Build with Maven
        run: mvn clean package

      
